import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from 'react'
import {weaviateMagic} from '../methods/weaviate'
import Plants from "../components/Plants"

export default function Home() {

  const [keyword, setKeyword] = useState("")
  const [plants, setPlants] = useState(null)
  const [isSearching, setIsSearching] = useState(false)

  async function onSubmit(e){
    e.preventDefault()
    console.log(keyword)
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <form onSubmit={onSubmit}>
        <input 
          type="search"
          value={keyword}
          onChange={(e) => setKeyword(e.target.value)}
        />
        <button
          style={{ height: "55px" }}
          onClick={() => weaviateMagic(keyword, setPlants, setIsSearching)}
        >
        {isSearching ? 'Searching...' : 'Search'}
        </button>
      </form>
      {plants
        ? plants.map((plant, idx) => (
          <Plants plant={plant} key={idx} />
        ))
      : null}
    </div>
  )
}
